#include "modules/register_module_types.h"

void initialize_blendalot_animgraph_module(ModuleInitializationLevel p_level);
void uninitialize_blendalot_animgraph_module(ModuleInitializationLevel p_level);
